---
title: "Erkan Fidan's resume"
author: Selcuk Erkan Fidan
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> selcukerkanfidan@gmail.com 
- <i class="fa fa-phone"></i> +1 607 759 5664
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Experienced in Microsoft Office.

- Full experience with MAC OS X

- Highly skilled in Google Office Applications

- Sql Software (pentagon 2000)

Language {#language}
--------------------------------------------------------------------------------

- Turkish (native)

- English (bilingual)

- German (elementary)

- Italian (elementary) 





Main
================================================================================

Selcuk Erkan Fidan {#title}
--------------------------------------------------------------------------------

### Operation Manager




Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Ayşeabla Private Schools

Primary School and Elementary School 

Ankara, Turkey

2004 - 2012



### Ümitköy Anatolian High School

 High School

Ankara, Turkey

2012 - 2015



### Private Sembol High School 

High School

Ankara, Turkey

2015 - 2016



### Middle East Technical University

Business Administration (International Joint Program) 

Ankara, Turkey

2016 - 2020



### Binghamton University

Business Administration (Dual Diploma Program) 

Binghamton, United States

2016 - 2020


Relevant Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Operation Manager

TabcoTech Enterprises

New York, United States

2021 - present

- Receiving products & Quality control
- Declaration to the state, setting a schedule and reassignment to customers.


### BU TURCA (Turkish Cultural Association)

President  

Binghamton, United States

2020 - 2021

- Set online career summits and assist Turkish community in Covid-19 circumstances 

### Intern at Akfen Holding



Ankara, Turkey

 2018

- Worked for finance department to help the employees in terms of organizing, documenting and
accounting



### Finance Conference ’17 

METU, Ankara

2017
  

Overseas Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### University of Portsmouth 

Summer Language School

Portshmouth, United Kingdom

2011



### University of Westminster

Summer Language School 

London, United Kingdom

2014



### CASA OVERSEAS Youth Work camp 

Voluntarily Work Camp for Refugees, building bungalow houses for their needs

Spilamberto, Italy

2019


Other Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Semi-pro basketball player

3x Turkish Youth Basketball National Championship (Played for Türk Telekom & Mavi Birlik)

Ankara, Turkey

2006 - 2014

### Semi-pro piano player 

Many private concerts and attended school organizations

2004 - present


Certificates {data-icon=file}
--------------------------------------------------------------------------------

### Dangerous Goods & Cargo Security Training

Global Transport Training Services USA, Ltd.

2021






 
